x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.0
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@pg-pagarme:5432/airflow
    TEAMS_WEBHOOK: ${TEAMS_WEBHOOK}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./etl:/opt/airflow/etl
    - ./db:/opt/airflow/db
    - ./data:/opt/airflow/data
    - ./alerts:/opt/airflow/alerts
  user: "${AIRFLOW_UID:-50000}:0"

services:
  pg-pagarme:
    image: postgres:13
    container_name: pg-pagarme
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./db:/opt/airflow/db   

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8085:8080"
    depends_on:
      - airflow-scheduler
      - airflow-init
      - pg-pagarme

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init
      - pg-pagarme

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db init && airflow users create \
        --username admin \
        --password admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email abner.lima@linx.com.br"
    depends_on:
      - pg-pagarme

volumes:
  postgres-db-volume: {}
